# Site settings
title: BiMech Blog
email: frank@binarymechanics.com
description: Thoughts on building and testing software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://binarymechanics.com" # the base hostname & protocol for your site
twitter_username: binarymechanics

# Build settings
markdown: kramdown
